image: alpine
variables:
  WORK_DIR: ${CI_PROJECT_NAME}
  BRANCH: ${CI_COMMIT_REF_NAME}
  REPO: https://gitlab.com/Tecnonucleous/open-telegram-bot-nodejs.git
  SERVER_IP: $SERVER_IP
  SERVER_PORT: $SERVER_PORT
  SSH_USERNAME: $SSH_USERNAME
  DEPLOY_KEY : $DEPLOY_KEY
stages:
  - deploy

deploy:
 stage: deploy
# Within before_script what we are doing is creating and adding ssh key, also we are disabling command line to ask for password. 'StrictHostKeyChecking no'
 before_script:
  - apk add --update openssh bash openssl gettext
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$DEPLOY_KEY" > MyKey
  - mv MyKey ~/.ssh/id_rsa
  - chmod 700  ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-keyscan -H domain.com >> ~/.ssh/known_hosts

 script:
  - ssh -o StrictHostKeyChecking=no "$SSH_USERNAME"@"$SERVER_IP" -p "$SERVER_PORT" "cd ${WORK_DIR}; git init; git clone -b ${BRANCH} ${REPO};"